name: Elixir CI

on:
  push:
    branches: 
      - master
      - 'feature/test-gigalixir'
  pull_request:
    branches: [ master ]

jobs:
  build:

    name: Build
    runs-on: ubuntu-latest

    env:
      MIX_ENV: 'test'
      NETATMO_APP_ID: ${{ secrets.NETATMO_APP_ID }}
      NETATMO_CLIENT_SECRET: ${{ secrets.NETATMO_CLIENT_SECRET }}
      NETATMO_USER_EMAIL: ${{ secrets.NETATMO_USER_EMAIL }}
      NETATMO_USER_PASSWORD: ${{ secrets.NETATMO_USER_PASSWORD }}
      ALTERVISTA_USER: ${{ secrets.ALTERVISTA_USER }}
      ALTERVISTA_PASSWORD: ${{ secrets.ALTERVISTA_PASSWORD }}

    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Set up Elixir
        uses: actions/setup-elixir@v1
        with:
          elixir-version: '1.11.0' # Define the elixir version [required]
          otp-version: '23.1.4' # Define the OTP version [required]
          experimental-otp: true
      - name: Restore dependencies and build cache
        uses: actions/cache@v2
        with:
          path: |
            deps
            _build
          key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: ${{ runner.os }}-mix-
      - name: Install dependencies
        run: mix deps.get
      - name: Build
        run: mix compile
    
  test:

    name: Test
    runs-on: ubuntu-latest
    needs: build

    env:
      MIX_ENV: 'test'
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # for coveralls
      NETATMO_APP_ID: ${{ secrets.NETATMO_APP_ID }}
      NETATMO_CLIENT_SECRET: ${{ secrets.NETATMO_CLIENT_SECRET }}
      NETATMO_USER_EMAIL: ${{ secrets.NETATMO_USER_EMAIL }}
      NETATMO_USER_PASSWORD: ${{ secrets.NETATMO_USER_PASSWORD }}
      ALTERVISTA_USER: ${{ secrets.ALTERVISTA_USER }}
      ALTERVISTA_PASSWORD: ${{ secrets.ALTERVISTA_PASSWORD }}

    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Set up Elixir
        uses: actions/setup-elixir@v1
        with:
          elixir-version: '1.11.0' # Define the elixir version [required]
          otp-version: '23.1.4' # Define the OTP version [required]
          experimental-otp: true
      - name: Restore dependencies and build cache
        uses: actions/cache@v2
        with:
          path: |
            deps
            _build
          key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: ${{ runner.os }}-mix-
      - name: Start PostgreSQL
        uses: harmon758/postgresql-action@v1
        with:
          postgresql version: '11'
          postgresql db: "webcam_fornolo_test"
          postgresql user: "user"
          postgresql password: "pass"
      - name: Run DB migrations
        run: mix ecto.setup
      - name: Run tests
        run: mix coveralls.github --trace
    
  deploy:

    name: Deploy to Gigalixir
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/feature/test-gigalixir'

    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8.1
      - uses: mhanberg/gigalixir-action@v0.6.1
        with:
          GIGALIXIR_APP: webcamfornolo
          GIGALIXIR_CLEAN: true # defaults to false
          GIGALIXIR_USERNAME: ${{ secrets.GIGALIXIR_USERNAME }}
          GIGALIXIR_PASSWORD: ${{ secrets.GIGALIXIR_PASSWORD }}
          MIGRATIONS: false  # defaults to true
